#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE
#define GRAVE_ESC_CTRL_OVERRIDE
#define RGBLIGHT_LAYERS
#define RGB_MATRIX_DEFAULT_HUE 130
// #define RGB_MATRIX_DEFAULT_HUE 200 //purple
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 255


#define RGB_MATRIX_TIMEOUT 1200000     // 20 minutes (20 * 60 * 1000ms)
#define RGB_DISABLE_WHEN_USB_SUSPENDED